name: run my vanilla Cypress tests
on: 
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      

      - name: Install dependencies
        working-directory: ./backend
        run: go get -v ./...

      - name: mod file matches the source code in the module
        working-directory: ./backend
        run: go mod tidy   

      - name: running backend go
        working-directory: ./backend
        run: go run main.go  

  frontend:
    needs: backend
    runs-on: ubuntu-latest
    steps:      
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Node
        working-directory:  ./frontend
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'   
        run: |
          npm install
          npm start

  frontend-testing:
    needs: frontend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
        build: npm run build
        start: npm start

    

