name: Running Tests On Endpoints

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: mod file matches the source code in the module
      working-directory: ./backend
      run: go mod tidy  

    - name: Install dependencies
      working-directory: ./backend
      run: go get -v ./...

    - name: Build compiles the packages, along with their dependencies
      working-directory: ./backend
      run: go build  
        
    - name: Run tests
      working-directory: ./backend
      run: go test -v ./...

    - name: Run check test code coverage
      working-directory: ./backend
      run: go test -v ./*.go -race -coverprofile=coverage.out -covermode=atomic
        
    - name: upload coverage to Codecov
      uses: codecov/codecov-action@v2